services:
  client:
    image: injurka/trip-scheduler-client:${V_CLIENT:-latest}
    container_name: trip-scheduler-client
    ports:
      - "1420:1420"
    restart: always
    networks:
      - trip-net

  server:
    image: injurka/trip-scheduler-server:${V_SERVER:-latest}
    container_name: trip-scheduler-server
    ports:
      - "8080:8080"
    networks:
      - trip-net
    env_file:
      - ../apps/server/.env
    volumes:
      - "$HOME/static-data:/usr/src/app/static"
    restart: always
    depends_on:
      db:
        condition: service_healthy

  directus:
    image: directus/directus:11.14.0
    container_name: trip-scheduler-admin
    ports:
      - "8055:8055"
    networks:
      - trip-net
    restart: always
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    volumes:
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
    env_file:
      - .env.database
      - .env.directus

  cache:
    image: redis:7-alpine
    container_name: trip-scheduler-cache
    networks:
      - trip-net
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    restart: always

  db:
    image: postgres:16-alpine
    container_name: trip-scheduler-db
    networks:
      - trip-net
    env_file:
      - .env.database
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - trip-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    depends_on:
      server:
        condition: service_started

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - trip-net
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/
    restart: always
    depends_on:
      prometheus:
        condition: service_started

  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    networks:
      - trip-net
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

networks:
  trip-net:
    driver: bridge

volumes:
  pgdata:
  prometheus-data:
  grafana-data:
  directus-uploads:
  directus-extensions:
